title: EFStudio
description: Minimal visual database studio for EF Core apps.
baseurl: "/EFStudio"
url: "https://carloslespin.github.io"
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
plugins: []
exclude:
  - Gemfile
  - Gemfile.lock
